  <?php echo $this->doctype() ?>
 <html>
 <head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />   
   <?php 
   		
   		$this->headLink()->appendStylesheet('/styles/style.css');		
		$this->headLink()->appendStylesheet('/styles/dp-style.css');
		$this->headLink()->appendStylesheet('/styles/datepicker.css');
		$this->headScript()->appendFile('/js/jQuery.js');
		$this->headScript()->appendFile('/js/jQuery-UI.js');
		$this->headScript()->appendFile('/js/script.js');		
		echo $this->headLink();
		echo $this->headScript();
   ?>

   	<title>ZF Guestbook</title>  
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Zend Framework Application</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'library'),
            'default',
            true) ?>">Library guestbook</a>
     </div>
</div>
<div id="menu">
	<a href="<?php echo $this->url(
            array('controller'=>'book'),
            'default',
            true) ?>">Books</a>
	
	<br /> 	
	<a href="<?php echo $this->url(
            array('controller'=>'author'),
            'default',
            true) ?>">Authors</a>
 	
	<br />
 	<a href="<?php echo $this->url(
            array('controller'=>'publisher'),
            'default',
            true) ?>">Publishers</a>
 
	<br />
 	<a href="<?php echo $this->url(
            array('controller'=>'genre'),
            'default',
            true) ?>">Genres</a>
	<br />
 	<a href="<?php echo $this->url(
            array('controller'=>'editor'),
            'default',
            true) ?>">Editors</a>
    <br />
 	<a href="<?php echo $this->url(
            array('controller'=>'address'),
            'default',
            true) ?>">Addresses</a>
	<br />
 	<a href="<?php echo $this->url(
            array('controller'=>'country'),
            'default',
            true) ?>">Countries</a>
	<br />
</div>
<?php echo $this->layout()->content ?>
	<div id='footer'>
		Chernivtsi, 2014
	</div>
</body>
 </html>